export const Add_Units = [
  { label: "Name Of Property", name: "propertyName", type: "text" },
  { label: "Location / Area", name: "location", type: "text" },
  { label: "City", name: "city", type: "text" },
  { label: "State", name: "state", type: "text" },
  { label: "Country", name: "country", type: "text" },
  { label: "Status", name: "status", type: "text" },
  { label: "Price / Rent", name: "rentPrice", type: "text" },
  { label: "No. of Rooms", name: "rooms", type: "text" },
  { label: "No. of Floors", name: "floors", type: "text" },
  { label: "Amenities", name: "amenities", type: "text" },
  { label: "View", name: "view", type: "text" },
  { label: "Name of Owner", name: "ownerName", type: "text" },
  { label: "Name of Tenant", name: "tenantName", type: "text" },
  { label: "Contact Number of Tenant", name: "contact", type: "text" },
];

export const Add_Property = [
  { label: "Name Of Property", name: "propertyName", type: "text" },
  { label: "Location", name: "location", type: "text" },
  { label: "No. of Units", name: "units", type: "text" },
  { label: "City", name: "city", type: "text" },
  { label: "State", name: "state", type: "text" },
  { label: "Postcode", name: "postcode", type: "text" },
  { label: "Country", name: "country", type: "text" },
  { label: "Status", name: "status", type: "text" },
  { label: "Price / Rent", name: "rentPrice", type: "text" },
];

export const Add_Tenant = [
  { label: "Name Of Property", name: "propertyName", type: "text" },
  { label: "Location / Area", name: "location", type: "text" },
  { label: "Number of Units", name: "units", type: "text" },
  { label: "City", name: "city", type: "text" },
  { label: "State", name: "state", type: "text" },
  { label: "Postcode", name: "postcode", type: "text" },
  { label: "Country", name: "country", type: "text" },
  { label: "Status", name: "status", type: "text" },
  { label: "Price / Rent", name: "rentPrice", type: "text" },
  { label: "Name of Tenant", name: "tenantName", type: "text" },
  { label: "Contact Number", name: "contact", type: "text" },
  { label: "Residence", name: "residence", type: "text" },
  { label: "Nationality", name: "nationality", type: "text" },
  { label: "Type", name: "type", type: "text" },
  { label: "Email", name: "email", type: "text" },
  { label: "Passport Number", name: "passportNum", type: "text" },
  { label: "Emirates ID", name: "emiratesId", type: "text" },
  { label: "Lease In Date", name: "leaseInDate", type: "date" },
  { label: "Lease Out Date", name: "leaseOutDate", type: "date" },
  { label: "Name of Owner", name: "ownerName", type: "text" },
  { label: "Contact Number of Owner", name: "ownerContact", type: "text" },
];

export const Add_Owner = [
  { label: "Name of Owner", name: "ownerName", type: "text" },
  { label: "Contact Number of Owner", name: "ownerContact", type: "text" },
  { label: "Email", name: "email", type: "text" },
  { label: "Number Of Property", name: "propertyCount", type: "text" },
  { label: "Number of Units", name: "units", type: "text" },
  { label: "Location / Area", name: "location", type: "text" },
  { label: "City", name: "city", type: "text" },
  { label: "State", name: "state", type: "text" },
  { label: "Postcode", name: "postcode", type: "text" },
  { label: "Country", name: "country", type: "text" },
  { label: "Residence", name: "residence", type: "text" },
  { label: "Nationality", name: "nationality", type: "text" },
  { label: "Passport Number", name: "passportNum", type: "text" },
  { label: "Emirates ID", name: "emiratesId", type: "text" },
];

export const Add_Lead = [
  { label: "Name Of Property", name: "propertyName", type: "text" },
  { label: "Location / Area", name: "location", type: "text" },
  { label: "Number of Units", name: "unitCount", type: "text" },
  { label: "City", name: "city", type: "text" },
  { label: "State", name: "state", type: "text" },
  { label: "Postcode", name: "postcode", type: "text" },
  { label: "Country", name: "country", type: "text" },
  { label: "Status", name: "status", type: "text" },
  { label: "Price / Rent", name: "rentPrice", type: "text" },
  { label: "Name of Lead", name: "leadName", type: "text" },
  { label: "Contact Number", name: "contact", type: "text" },
  { label: "Residence", name: "residence", type: "text" },
  { label: "Nationality", name: "nationality", type: "text" },
  { label: "Type", name: "type", type: "text" },
  { label: "Email", name: "email", type: "text" },
  { label: "Passport Number", name: "passportNum", type: "text" },
  { label: "Emirates ID", name: "emiratesId", type: "text" },
  { label: "Lease In Date", name: "leaseInDate", type: "text" },
  { label: "Lease Out Date", name: "leaseOutDate", type: "text" },
  { label: "Name of Owner", name: "ownerName", type: "text" },
  { label: "Contact Number of Owner", name: "ownerContact", type: "text" },
];

export const Add_BookReserve = [
  { label: "Name Of Property", name: "propertyName", type: "text" },
  { label: "Location / Area", name: "location", type: "text" },
  { label: "Number of Units", name: "unitCount", type: "text" },
  { label: "City", name: "city", type: "text" },
  { label: "State", name: "state", type: "text" },
  { label: "Postcode", name: "postcode", type: "text" },
  { label: "Country", name: "country", type: "text" },
  { label: "Status", name: "status", type: "text" },
  { label: "Date of booking", name: "bookingDate", type: "text" },
  { label: "Name of Tenant", name: "tenantName", type: "text" },
  { label: "Contact Number", name: "contact", type: "text" },
  { label: "Residence", name: "residence", type: "text" },
  { label: "Nationality", name: "nationality", type: "text" },
  { label: "Type", name: "type", type: "text" },
  { label: "Email", name: "email", type: "text" },
  { label: "Passport Number", name: "passportNum", type: "text" },
  { label: "Emirates ID", name: "emiratesId", type: "text" },
  { label: "Start Date", name: "endDate", type: "text" },
  { label: "End Date", name: "startDate", type: "text" },
  { label: "No. of Cheques", name: "chequesCount", type: "text" },
  { label: "Rent Amount to Pay", name: "payAmount", type: "text" },
  { label: "Name of Unit", name: "unitName", type: "text" },
  { label: "Booking Amount", name: "bookingAmount", type: "text" },
  { label: "Name of Owner", name: "ownerName", type: "text" },
  { label: "Contact Number of Owner", name: "ownerContact", type: "text" },
];

export const Add_TenancyContractTenant = [
  { label: "Name Of Property", name: "propertyName", type: "text" },
  { label: "Location / Area", name: "location", type: "text" },
  { label: "Name of Tenant", name: "tenantName", type: "text" },
  { label: "Tenant Contact Number", name: "tenantContact", type: "text" },
  { label: "Email", name: "email", type: "text" },
  { label: "No. of Cheques", name: "chequesCount", type: "text" },
  { label: "Rent Amount to Pay", name: "payAmount", type: "text" },
  { label: "Number of Unit", name: "unitCount", type: "text" },
  { label: "Lease In Date", name: "leaseInDate", type: "text" },
  { label: "Lease Out Date", name: "leaseOutDate", type: "text" },
  { label: "Status", name: "status", type: "text" },
  { label: "Residence", name: "residence", type: "text" },
  { label: "Emirates ID", name: "emiratesId", type: "text" },
  { label: "City", name: "city", type: "text" },
  { label: "Image Attachment", name: "doc", type: "text" },
  { label: "Price / Rent Annually", name: "anualPriceRent", type: "text" },
  { label: "Type", name: "type", type: "text" },
];

export const Add_TenancyContractOwner = [
  { label: "Name Of Owner", name: "ownerName", type: "text" },
  { label: "Contact Number of Owner", name: "ownerContact", type: "text" },
  { label: "Emirates ID", name: "emiratesId", type: "text" },
  { label: "Residence", name: "residence", type: "text" },
  { label: "Country", name: "country", type: "text" },
  { label: "Email", name: "email", type: "text" },
  { label: "Mobile Number", name: "mobileNumber", type: "text" },
  { label: "Image Attachment", name: "doc", type: "text" },
  { label: "Signature of Owner", name: "signOwner", type: "text" },
  { label: "Signature of Tenant", name: "signTenant", type: "text" },
  { label: "Digital Signature of Owner", name: "digitalSign", type: "text" },
];
